### ISSUE TITLE
Serverside Issue - Unable to Login ( Being Timed Out )

### ISSUE THREAD

**Issue by EnderN4T** [P3rf3ctXZer0/mc-1.15.2-Pokecube-Evolved#7]
[2020-06-13-3.log.gz](https://github.com/P3rf3ctXZer0/mc-1.15.2-Pokecube-Evolved/files/4775767/2020-06-13-3.log.gz)

**Comment by P3rf3ctXZer0** [comment]
I am not yet sure what causes this. Maybe something with forge? I will keep my eyes peeled it has to be something right? @Thutmose the logs don't seem to say much server or clientside.

**Comment by P3rf3ctXZer0** [comment]
@EnderN4T what were you doing when this started? Where were you? What npcs are nearby did this start after adding or removing a mod?

**Comment by P3rf3ctXZer0** [comment]
Unable to actually fix but by making a new world it seems to no longer be an issue -- most likely a corrupted player nbt.
